server:
  port: 8080

spring:
  application:
    name: my-app

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

downstream:
  service-a:
    base-url: ${DOWNSTREAM_SERVICE_A_BASE_URL:http://localhost:8081}
  service-b:
    base-url: ${DOWNSTREAM_SERVICE_B_BASE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
